Milestone4:Desktop version of the project
ismayito/Portfolio- pull request #5
Opened 2023-02-22 16:41 UTC by ismayito

#Desktop version and responsiveness
In this milestone; We added the following.
- The desktop version on the project and also made it responsive

2023-02-22 17:16 UTC, levy002 requested changes
## Hello @ismayito   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Highlights
- Professional PR :heavy_check_mark: 

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [ ] Kindly make sure to add enough padding on both sides of the navigation bar in order to match the provided Figma design.

   - ### YOUR DESIGN
   
    ![image](https://user-images.githubusercontent.com/87197412/220704722-4562b1ea-1194-4b37-814c-a3ca1d4df84f.png)

   - ### FIGMA DESIGN
    
    ![image](https://user-images.githubusercontent.com/87197412/220704855-be526fc1-e6c4-4f0d-90f3-c6e991927efe.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 17:16 UTC, levy002 commented on style.css
> +}
- [ ] Kindly make sure to align the project information in its card correctly in order to match the Figma design as much as possible.

  - ### YOUR DESIGN
  
    ![image](https://user-images.githubusercontent.com/87197412/220700739-1b9b1e5d-1e4e-41d8-acea-d5a0e01dc1b3.png)

  - ### FIGMA DESIGN
  
   ![image](https://user-images.githubusercontent.com/87197412/220701108-2a4f8342-07fa-4de5-a3f0-0136f393e952.png)

2023-02-22 17:16 UTC, levy002 commented on style.css
> +  }
- [ ] Kindly make sure to provide enough padding on both sides of the `About-me` section in order to match the Figma design as much as possible. 

- [ ] Kindly make sure your `Get my resue` button width is the same as the one Figma design.

  - ### YOUR DESIGN
  
    ![image](https://user-images.githubusercontent.com/87197412/220702634-64ed78d2-50b5-49ce-b8da-d3224cfcc281.png)

  - ### FIGMA DESIGN
  
    ![image](https://user-images.githubusercontent.com/87197412/220702855-f77eb26d-8c28-4270-a511-61ab149ad671.png)

2023-02-22 17:16 UTC, levy002 commented on style.css
> +  }
- [ ] Kindly make sure the `Languages` card has the same height and width as the one on the Figma design.

   - ### YOUR DESIGN
   
     ![image](https://user-images.githubusercontent.com/87197412/220703282-842e50f1-a92b-40f9-b89a-76639ad45809.png)

   - ### FIGMA DESIGN
   
    ![image](https://user-images.githubusercontent.com/87197412/220703444-3b3b0e23-5164-4ffc-bcab-8df0b4ddb560.png)

2023-02-23 10:14 UTC, mahbubul14 approved these changes
# Project Approved :trophy: :tada: 

Hi @ismayito, 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linter error.
:heavy_check_mark: Descriptive readme file.
:heavy_check_mark: Well-implemented suggestions.

### Optional suggestions :arrow_down_small: 

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

- [ ] The commit message should be written in the imperative tense and the first letter should also be capitalized. `Ex: "Fix bug" instead of "fix bug".` [For more details...](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-02-23 12:20 UTC, merged